services:
    seq:
        image: datalust/seq
        container_name: seq
        restart: always
        environment:
            ACCEPT_EULA: Y
        ports:
            - "5341:80"
        volumes:
            - ./Source/MonitoringService/MonitoringService.Host/logs:/data