//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringService.Application.SqlScripts {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitoringService.Application.SqlScripts.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO public.&quot;Statistics&quot; (&quot;Id&quot;,&quot;DeviceName&quot;,&quot;OperatingSystem&quot;,&quot;Version&quot;,&quot;LastUpdateDateTime&quot;)
        ///VALUES (@Id,@DeviceName,@OperatingSystem,@Version,@LastUpdateDateTime)
        ///RETURNING &quot;Id&quot;;.
        /// </summary>
        internal static string AddStatistics {
            get {
                return ResourceManager.GetString("AddStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Statistics&quot; WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string DeleteStatistics {
            get {
                return ResourceManager.GetString("DeleteStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT count(1) FROM  &quot;Statistics&quot; WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string ExistsStatistics {
            get {
                return ResourceManager.GetString("ExistsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,&quot;DeviceName&quot;,&quot;OperatingSystem&quot;,&quot;Version&quot;,&quot;LastUpdateDateTime&quot; FROM &quot;Statistics&quot;;.
        /// </summary>
        internal static string GetAllStatistics {
            get {
                return ResourceManager.GetString("GetAllStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,&quot;DeviceName&quot;,&quot;OperatingSystem&quot;,&quot;Version&quot;,&quot;LastUpdateDateTime&quot; FROM &quot;Statistics&quot;
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string GetStatistics {
            get {
                return ResourceManager.GetString("GetStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Statistics&quot;
        ///SET
        ///    &quot;Id&quot; = @Id,
        ///    &quot;DeviceName&quot; = @DeviceName,
        ///    &quot;OperatingSystem&quot; = @OperatingSystem,
        ///    &quot;Version&quot; = @Version,
        ///    &quot;LastUpdateDateTime&quot; = @LastUpdateDateTime
        ///WHERE &quot;Id&quot; = @Id;.
        /// </summary>
        internal static string UpdateStatistics {
            get {
                return ResourceManager.GetString("UpdateStatistics", resourceCulture);
            }
        }
    }
}
