services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: StatisticsService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  statisticsService:
    image: monitoring-service:dev-build
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-build
    ports:
    - "5000:80"
    environment:
      - ConnectionStrings__StatisticsDatabaseConnection=Host=localhost;Port=5432;Database=StatisticsService;Username=postgres;Password=postgres
    depends_on:
      postgres: 
        condition: service_healthy
  
  seq:
        image: datalust/seq
        container_name: seq
        restart: always
        environment:
            ACCEPT_EULA: Y
        ports:
            - "5341:80"
        volumes:
            - ./MonitoringService.Host/logs:/data

volumes:
  pgdata: